<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sdml</string>
		<string>sdm</string>
	</array>
	<key>name</key>
	<string>SDML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?x)  \b(module)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)  (?:\s+(base)\s+((\&lt;)(?:[^\x00-\x20\&lt;\&gt;\\\"\{\}\|\^`]|(?:\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8}))*(\&gt;)))?  \s+  (is)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.sdml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.base.sdml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.iri.sdml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.iri.begin.sdml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.iri.end.sdml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.other.is.sdml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Module (Top-Level) Declaration</string>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.end.sdml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.module.sdml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Import Statement</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\b(import)\b\s*(\[)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.import.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.sequence.begin.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\]</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.sequence.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.literal.sequence.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\b(?:dcam|dcel|dc|owl|rdf|rdfs|sdml|xml|xsd):[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*\b</string>
									<key>name</key>
									<string>support.class.std.sdml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*:[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*\b</string>
									<key>name</key>
									<string>support.class.sdml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b(?:dcam|dcel|dc|owl|rdf|rdfs|sdml|xml|xsd)\b</string>
									<key>name</key>
									<string>support.other.module.std.sdml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\b[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*\b</string>
									<key>name</key>
									<string>support.other.module.sdml</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.import.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>support.class.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(import)\b\s*([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*:[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.control.import.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>support.other.module.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(import)\b\s*([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation_property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation_constraint</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Product Type Declarations</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?x)
								\b(datatype)\b
								\s+
								([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
								\s*
								((?:&lt;-)|←)
								\s*
								(?:(opaque)\s+)?
								([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)
								\s+
								(is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.datatype.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.datatype.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.type-restriction.sdml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>keyword.other.opaque.sdml</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>support.class.sdml</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>keyword.other.is.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.datatype.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.datatype.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.datatype.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.type-restriction.sdml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>keyword.other.opaque.sdml</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>support.class.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?x)
								\b(datatype)\b
								\s+
								([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
								\s*
								((?:&lt;-)|←)
								\s*
								(?:(opaque)\s+)?
								([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)</string>
							<key>name</key>
							<string>meta.declaration.datatype.sdml</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(entity)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s+(is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.entity.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.entity.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.is.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.entity.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#identity_member_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#member_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.entity.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.entity.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(entity)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
							<key>name</key>
							<string>meta.declaration.entity.sdml</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(event)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s*(source)\s*([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)\s+(is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.event.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.event.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.source.sdml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.event-source.sdml</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>keyword.other.is.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.event.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#member_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.event.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.event.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.source.sdml</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>entity.other.event-source.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(event)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s*(source)\s*([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)</string>
							<key>name</key>
							<string>meta.declaration.event.sdml</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(property)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s+(is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.property.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.property.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.is.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.property.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#member_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.property.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.property.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(property)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
							<key>name</key>
							<string>meta.declaration.property.sdml</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(structure)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s+(is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.structure.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.structure.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.is.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.structure.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#member_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.structure.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.structure.sdml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\b(structure)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
							<key>name</key>
							<string>meta.declaration.structure.sdml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Sum Type Declarations</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?x)  \b(enum)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)  \s+  (of)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.enum.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.enum.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.of.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.enum.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#value_variant</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?x)  \b(union)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)  \s+  (of)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.union.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.union.sdml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.other.of.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.union.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#type_variant</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Class Declarations</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?x)  \b(class)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*) (\() (.*) (\))  \s+  (is)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.type.class.sdml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.type.class.sdml</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>keyword.other.of.sdml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\bend\b</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.other.end.sdml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.declaration.class.sdml</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#annotation_property</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#annotation_constraint</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#method_def</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#line_comment</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotation_constraint</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.assert.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.assertion.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.sdml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Informal Constraint</string>
					<key>match</key>
					<string>(?x)  \b(assert)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)  \s*  (=)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)  \b(assert)\b  \s+  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)  \s+  (is)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.assert.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.assertion.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.is.sdml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Formal Constraint</string>
					<key>end</key>
					<string>\bend\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.end.sdml</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#method_def</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\bin\b</string>
							<key>name</key>
							<string>keyword.other.in.sdml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>annotation_only_body</key>
		<dict>
			<key>begin</key>
			<string>\bis\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.is.sdml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.end.sdml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#annotation_property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation_constraint</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<key>annotation_property</key>
		<dict>
			<key>comment</key>
			<string>Annotation Property</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation.begin.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.annotation.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.sdml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@)([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)\s*(=)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>escaped_ascii_character</key>
		<dict>
			<key>match</key>
			<string>\\(a|b|n|r|t|v|\\|'|"|0)</string>
			<key>name</key>
			<string>constant.character.escape.sdml</string>
		</dict>
		<key>escaped_unicode_character</key>
		<dict>
			<key>match</key>
			<string>\\u\{(\h\h){1,3}\}</string>
			<key>name</key>
			<string>constant.character.escape.sdml</string>
		</dict>
		<key>expression_cardinality</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.cardinality.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.ordering.sdml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.uniqueness.sdml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sdml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.range.sdml</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.sdml</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.cardinality.sdml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(\{)\s*(?:(ordered|unordered)\s+)?(?:(unique|nonunique)\s+)?(\d+)(?:(\.\.)(\d+)?)?(\})\s*</string>
			<key>name</key>
			<string>meta.literal.cardinality.sdml</string>
		</dict>
		<key>identity_member_def</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.identity.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.member.sdml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hastype</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.class.sdml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(identity)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s*(-&gt;)\s*([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
			<key>name</key>
			<string>meta.declaration.member.identity.sdml</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.sdml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sdml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.semicolon.sdml</string>
				</dict>
			</array>
		</dict>
		<key>literal_binary</key>
		<dict>
			<key>begin</key>
			<string>\#\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.binary.begin.sdml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.binary.end.sdml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.literal.binary.sdml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\h\h</string>
					<key>name</key>
					<string>constant.numeric.byte.sdml</string>
				</dict>
			</array>
		</dict>
		<key>literal_boolean</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|⊤|⊥)\b</string>
			<key>name</key>
			<string>constant.language.boolean.sdml</string>
		</dict>
		<key>literal_empty_sequence</key>
		<dict>
			<key>begin</key>
			<string>\b∅\b</string>
			<key>name</key>
			<string>meta.literal.sequence.empty.sdml</string>
		</dict>
		<key>literal_iri</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.iri.begin.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.iri.end.sdml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) (\&lt;) (?:[^\x00-\x20\&lt;\&gt;\\\"\{\}\|\^`] | (?:\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8}))* (\&gt;)</string>
			<key>name</key>
			<string>constant.other.iri.sdml</string>
		</dict>
		<key>literal_numeric</key>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.sdml</string>
		</dict>
		<key>literal_sequence</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.sequence.begin.sdml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.sequence.end.sdml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.literal.sequence.sdml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simple_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value_constructor</string>
				</dict>
			</array>
		</dict>
		<key>literal_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.sdml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")(@[a-z]{2})?</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.language.sdml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.sdml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_ascii_character</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped_unicode_character</string>
				</dict>
			</array>
		</dict>
		<key>member_def</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.member.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.inverse_name.begin.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.member.sdml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.inverse_name.end.sdml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.has-type.sdml</string>
						</dict>
						<key>6</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expression_cardinality</string>
								</dict>
							</array>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.features.sdml</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.class.sdml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
						(?:
							\s*
							(\()
							([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
							(\))
							\s*
						)?
						\s*
						((?:-&gt;)|→)
						\s*
						(
							\s*
							\{.*\}
							\s*
						)?
						(?:(features)\s+)?
						([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)</string>
					<key>name</key>
					<string>meta.declaration.member.sdml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation_only_body</string>
				</dict>
			</array>
		</dict>
		<key>method_def</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.method.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.sdml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parameter</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.sdml</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.has-type.sdml</string>
						</dict>
						<key>7</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#expression_cardinality</string>
								</dict>
							</array>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>support.class.sdml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(def)\b\s+([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s*(?:(\()(.*)(\)))\s*((?:-&gt;)|→)\s*(\s*\{.*\}\s*)?([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)</string>
					<key>name</key>
					<string>meta.declaration.method.sdml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#annotation_only_body</string>
				</dict>
			</array>
		</dict>
		<key>method_expression</key>
		<dict>
			<key>match</key>
			<string>(?x)  ((?::=)|≔) </string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hastype</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression_cardinality</string>
						</dict>
					</array>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.class.sdml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)\s*((?:-&gt;)|→)\s*(\s*\{.*\}\s*)?([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)</string>
			<key>name</key>
			<string>meta.declaration.parameter.sdml</string>
		</dict>
		<key>simple_types</key>
		<dict>
			<key>match</key>
			<string>\b(boolean|unsigned|integer|decimal|double|string|iri|binary)\b</string>
			<key>name</key>
			<string>storage.type.sdml</string>
		</dict>
		<key>simple_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal_boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_iri</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_binary</string>
				</dict>
			</array>
		</dict>
		<key>type_variant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)
					(?:
						(?:
							([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)
							\s+  (as)  \s+  
							([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
						)
						|
						([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
					)
					\s+ (is)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.as.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.type.sdml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.type.sdml</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.other.is.sdml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\bend\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.end.sdml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.variant.type.sdml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#annotation_property</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#annotation_constraint</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.class.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.as.sdml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.type.sdml</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.type.sdml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
					(?:
						(?:
							([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)
							\s+  (as)  \s+  
							([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
						)
						|
						([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)
					)</string>
					<key>name</key>
					<string>meta.declaration.variant.type.sdml</string>
				</dict>
			</array>
		</dict>
		<key>unknown_type</key>
		<dict>
			<key>match</key>
			<string>\bunknown\b</string>
			<key>name</key>
			<string>storage.type.unknown.sdml</string>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simple_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value_constructor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_sequence</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal_empty_sequence</string>
				</dict>
			</array>
		</dict>
		<key>value_constructor</key>
		<dict>
			<key>begin</key>
			<string>([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*(?::[\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)?)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.name.sdml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.smdl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.arguments.end.smdl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#simple_value</string>
				</dict>
			</array>
		</dict>
		<key>value_variant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*) \s+ (is)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.value.sdml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.is.sdml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\bend\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.end.sdml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.variant.value.sdml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#annotation_property</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#annotation_constraint</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.variant.value.sdml</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)  ([\p{Lower}\p{Upper}][\p{Lower}\p{Upper}\p{Digit}]*(?:_[\p{Lower}\p{Upper}\p{Digit}]+)*)</string>
					<key>name</key>
					<string>meta.declaration.variant.value.sdml</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sdml</string>
	<key>uuid</key>
	<string>81CFF5F3-88BA-4D77-A897-16A2B546DBCF</string>
</dict>
</plist>
